"""D6 — external baselines, published. One reproducible script.

Runs two legs and prints a markdown report (also written to RESULTS.md):

  1. interpreter micro-suite: rad (release) vs Lua (via lupa) vs QuickJS
     (via the `quickjs` python binding) vs Node (V8, JIT — the one we
     expect to lose to, on purpose)
  2. the same 10k-edit collab script: rad fork_delta/fork_apply/merge vs
     Yjs vs Automerge (delta bytes + ingest ms)

Every implementation prints RESULT/CHECK lines; the harness REFUSES to
report a row whose results disagree across runtimes — apples stay apples.

  py benches/baselines/run_baselines.py
"""

import json
import pathlib
import statistics
import subprocess
import sys

HERE = pathlib.Path(__file__).parent
ROOT = HERE.parent.parent
RAD = ROOT / "target" / "release" / "rad.exe"
RUNS = 5

NODE_CANDIDATES = [
    "node",
    r"h:\Cursor\resources\app\resources\helpers\node.exe",
]


def find_node():
    import shutil
    for c in NODE_CANDIDATES:
        p = shutil.which(c) or (c if pathlib.Path(c).exists() else None)
        if p:
            return p
    return None


def parse_kv(text):
    out = {}
    for line in text.splitlines():
        parts = line.split()
        if len(parts) == 4 and parts[0] == "RESULT" and parts[2] == "MS":
            out["RESULT"] = parts[1]
            out["MS"] = float(parts[3])
        elif len(parts) == 2 and parts[0] in (
            "CHECK", "APPLY_MS", "DELTA_BYTES", "INGEST_MS", "MERGE_MS"
        ):
            out[parts[0]] = parts[1]
    return out


def run_rad(path):
    r = subprocess.run(
        [str(RAD), str(path)], capture_output=True, text=True, timeout=600
    )
    if r.returncode != 0:
        raise RuntimeError(f"rad {path.name}: {r.stderr[-400:]}")
    return parse_kv(r.stdout)


def lua_label():
    import lupa
    return f"Lua {'.'.join(map(str, lupa.LUA_VERSION))} (lupa)"


def run_lua(path):
    import lupa
    rt = lupa.LuaRuntime()
    lines = []
    rt.globals()["print"] = lambda s: lines.append(str(s))
    rt.execute(path.read_text())
    return parse_kv("\n".join(lines))


def run_quickjs(path):
    import quickjs
    ctx = quickjs.Context()
    lines = []
    ctx.add_callable("print_line", lambda s: lines.append(str(s)))
    ctx.eval(path.read_text())
    return parse_kv("\n".join(lines))


def run_node(node, path, cwd=None):
    src = path.read_text()
    if path.suffix == ".js":  # micro files use print_line
        src = "const print_line = console.log;\n" + src
        r = subprocess.run(
            [node, "--input-type=module", "-e", src],
            capture_output=True, text=True, timeout=600, cwd=cwd or HERE,
        )
    else:  # .mjs collab scripts run as files for package resolution
        r = subprocess.run(
            [node, str(path)],
            capture_output=True, text=True, timeout=600, cwd=cwd or path.parent,
        )
    if r.returncode != 0:
        raise RuntimeError(f"node {path.name}: {r.stderr[-400:]}")
    return parse_kv(r.stdout)


def median_runs(fn, runs=RUNS):
    """fn() -> kv dict. Returns kv of the median-MS run + result agreement."""
    samples = [fn() for _ in range(runs)]
    results = {s.get("RESULT") or s.get("CHECK") for s in samples}
    if len(results) != 1:
        raise RuntimeError(f"nondeterministic results across runs: {results}")
    key = "MS" if "MS" in samples[0] else "APPLY_MS"
    samples.sort(key=lambda s: float(s[key]))
    return samples[len(samples) // 2]


def main():
    node = find_node()
    if not RAD.exists():
        sys.exit("build first: cargo build --release -p rad-vm")

    report = ["# Baseline results (auto-generated by run_baselines.py)", ""]
    import platform
    report.append(
        f"Machine: {platform.processor() or platform.machine()}, "
        f"{platform.system()} {platform.release()}; "
        f"median of {RUNS} runs; times in ms (lower is better)."
    )
    report.append("")

    # ---- leg 1: micro-suite -------------------------------------------------
    micro = HERE / "micro"
    benches = ["fib", "loop_sum", "str_build", "sort"]
    rows = []
    for b in benches:
        row = {"bench": b}
        cross = {}

        kv = median_runs(lambda: run_rad(micro / f"{b}.rad"))
        row["rad"] = kv["MS"]
        cross["rad"] = kv["RESULT"]

        kv = median_runs(lambda: run_lua(micro / f"{b}.lua"))
        row["lua"] = kv["MS"]
        cross["lua"] = kv["RESULT"]

        kv = median_runs(lambda: run_quickjs(micro / f"{b}.js"))
        row["qjs"] = kv["MS"]
        cross["qjs"] = kv["RESULT"]

        if node:
            kv = median_runs(lambda: run_node(node, micro / f"{b}.js"))
            row["node"] = kv["MS"]
            cross["node"] = kv["RESULT"]

        if len(set(cross.values())) != 1:
            raise RuntimeError(f"{b}: implementations disagree: {cross}")
        rows.append(row)

    report.append("## Interpreter micro-suite")
    report.append("")
    hdr = f"| bench | rad | {lua_label()} | QuickJS (py binding) | Node (V8 JIT) |"
    report.append(hdr)
    report.append("|---|---|---|---|---|")
    for r in rows:
        report.append(
            f"| {r['bench']} | {r['rad']:.0f} | {r['lua']:.0f} | "
            f"{r['qjs']:.0f} | {r.get('node', float('nan')):.0f} |"
        )
    report.append("")

    # ---- leg 2: the 10k-edit collab script ----------------------------------
    collab = HERE / "collab"
    crows = {}
    crows["rad (fork_delta/apply/merge)"] = median_runs(
        lambda: run_rad(collab / "edits.rad")
    )
    if node:
        crows["Yjs"] = median_runs(lambda: run_node(node, collab / "edits_yjs.mjs"))
        crows["Automerge"] = median_runs(
            lambda: run_node(node, collab / "edits_automerge.mjs")
        )

    checks = {k: v["CHECK"] for k, v in crows.items()}
    if len(set(checks.values())) != 1:
        raise RuntimeError(f"collab: edit streams disagree: {checks}")

    report.append("## The same 10k-edit script (2000 cells), peer sync")
    report.append("")
    report.append("| system | apply 10k edits (ms) | delta bytes | peer ingest (ms) |")
    report.append("|---|---|---|---|")
    for name, kv in crows.items():
        report.append(
            f"| {name} | {float(kv['APPLY_MS']):.0f} | "
            f"{int(kv['DELTA_BYTES']):,} | {float(kv['INGEST_MS']):.0f} |"
        )
    extra = crows["rad (fork_delta/apply/merge)"].get("MERGE_MS")
    if extra is not None:
        report.append("")
        report.append(
            f"rad's three-way `merge_forks(base, ours, theirs)` on top of the "
            f"ingest: **{float(extra):.0f} ms** (Yjs/Automerge merge by CRDT "
            f"convergence instead; no comparable three-way step exists)."
        )
    report.append("")

    text = "\n".join(report)
    print(text)
    (HERE / "RESULTS.md").write_text(text, encoding="utf-8")
    (HERE / "results.json").write_text(
        json.dumps({"micro": rows, "collab": {k: v for k, v in crows.items()}}, indent=2),
        encoding="utf-8",
    )
    print(f"\nwritten: {HERE / 'RESULTS.md'} and results.json")


if __name__ == "__main__":
    main()
