"""Exact solver for union-closed families invariant under one permutation.

The permutation is specified by its coordinate-cycle lengths.  Subsets are
quotiented by the cyclic group generated by that permutation.  Union closure
becomes Horn clauses between subset orbits, while strict Frankl failure is one
weighted Boolean upper bound for every coordinate orbit.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from time import perf_counter

from pysat.solvers import Solver

from orbit_horn import iter_join_horn_clauses, orbit_owner, violated_join_horn_clauses
from weighted_cnf import encode_weighted_at_most


def parse_cycle_type(encoded: str, width: int) -> tuple[int, ...]:
    cycles = tuple(sorted((int(part) for part in encoded.split(",") if part), reverse=True))
    if any(length <= 0 for length in cycles) or sum(cycles) != width:
        raise ValueError(f"cycle lengths must be positive and sum to {width}")
    return cycles


def canonical_permutation(cycles: tuple[int, ...]) -> tuple[list[int], list[tuple[int, ...]]]:
    width = sum(cycles)
    permutation = list(range(width))
    coordinate_orbits: list[tuple[int, ...]] = []
    start = 0
    for length in cycles:
        orbit = tuple(range(start, start + length))
        coordinate_orbits.append(orbit)
        for offset, coordinate in enumerate(orbit):
            permutation[coordinate] = orbit[(offset + 1) % length]
        start += length
    return permutation, coordinate_orbits


def permute_mask(mask: int, permutation: list[int]) -> int:
    result = 0
    for source, target in enumerate(permutation):
        if mask >> source & 1:
            result |= 1 << target
    return result


def subset_orbits(permutation: list[int]) -> list[tuple[int, ...]]:
    cube_size = 1 << len(permutation)
    seen = [False] * cube_size
    result: list[tuple[int, ...]] = []
    for mask in range(cube_size):
        if seen[mask]:
            continue
        orbit = []
        current = mask
        while not seen[current]:
            seen[current] = True
            orbit.append(current)
            current = permute_mask(current, permutation)
        result.append(tuple(sorted(orbit)))
    return result


def solve(
    width: int,
    cycles: tuple[int, ...],
    separating: bool,
    max_subset_orbits: int,
    closure_mode: str,
    batch: int,
    rounds: int,
    output: Path | None,
) -> int:
    permutation, coordinate_orbits = canonical_permutation(cycles)
    orbits = subset_orbits(permutation)
    if len(orbits) > max_subset_orbits:
        print(
            f"result=skipped width={width} cycle_type={cycles} "
            f"subset_orbits={len(orbits)} limit={max_subset_orbits}"
        )
        return 2

    cube_size = 1 << width
    owner = orbit_owner(orbits, cube_size)
    clauses: list[list[int]] = []
    full_orbit = owner[cube_size - 1]
    clauses.append([full_orbit + 1])
    horn_count = 0
    if closure_mode == "eager":
        for left, right, target in iter_join_horn_clauses(orbits, owner):
            clauses.append([-(left + 1), -(right + 1), target + 1])
            horn_count += 1

    if separating:
        for left in range(width):
            for right in range(left + 1, width):
                clauses.append(
                    [
                        index + 1
                        for index, orbit in enumerate(orbits)
                        if any(((mask >> left) & 1) != ((mask >> right) & 1) for mask in orbit)
                    ]
                )

    variable_count = len(orbits)
    for coordinates in coordinate_orbits:
        signed_coefficients: list[int] = []
        for orbit in orbits:
            total_incidence = sum(
                sum(mask >> coordinate & 1 for coordinate in coordinates)
                for mask in orbit
            )
            assert total_incidence % len(coordinates) == 0
            signed_coefficients.append(2 * (total_incidence // len(coordinates)) - len(orbit))
        negative_total = sum(-coefficient for coefficient in signed_coefficients if coefficient < 0)
        terms = [
            ((index + 1) if coefficient > 0 else -(index + 1), abs(coefficient))
            for index, coefficient in enumerate(signed_coefficients)
            if coefficient
        ]
        variable_count, encoded = encode_weighted_at_most(variable_count, terms, negative_total - 1)
        clauses.extend(encoded)

    started = perf_counter()
    learned: set[tuple[int, int, int]] = set()
    model = None
    satisfiable = False
    with Solver(name="cadical195", bootstrap_with=clauses) as solver:
        for _round_index in range(rounds):
            satisfiable = solver.solve()
            if not satisfiable:
                break
            model = solver.get_model()
            if closure_mode == "eager":
                break
            positive = {literal for literal in model or [] if literal > 0}
            chosen = {index for index in range(len(orbits)) if index + 1 in positive}
            violations = violated_join_horn_clauses(chosen, orbits, owner, batch)
            inserted = 0
            for left, right, target in violations:
                clause = (left, right, target)
                if clause in learned:
                    continue
                learned.add(clause)
                solver.add_clause([-(left + 1), -(right + 1), target + 1])
                inserted += 1
            if not violations:
                break
            if inserted == 0:
                raise RuntimeError("lazy orbit separator produced no new Horn clause")
        else:
            print(
                f"result=round-limit width={width} cycle_type={cycles} "
                f"subset_orbits={len(orbits)} learned={len(learned)}"
            )
            return 2
    if closure_mode == "lazy":
        horn_count = len(learned)
    elapsed = perf_counter() - started

    document: dict[str, object] = {
        "schema": "rad.boolean-lattice.permutation-symmetry-proof.v1",
        "width": width,
        "cycle_type": list(cycles),
        "coordinate_orbit_count": len(coordinate_orbits),
        "subset_orbit_count": len(orbits),
        "horn_clause_count": horn_count,
        "cnf_variable_count": variable_count,
        "cnf_clause_count": len(clauses) + len(learned),
        "separating_required": separating,
        "counterexample_exists": satisfiable,
        "elapsed_seconds": elapsed,
        "solver": "cadical195",
        "closure_mode": closure_mode,
    }
    if satisfiable:
        positive = {literal for literal in model or [] if literal > 0}
        selected = {index for index in range(len(orbits)) if index + 1 in positive}
        family = sorted(mask for index in selected for mask in orbits[index])
        frequencies = [sum(mask >> bit & 1 for mask in family) for bit in range(width)]
        document.update(
            {
                "selected_orbits": sorted(selected),
                "family": family,
                "family_size": len(family),
                "frequencies": frequencies,
                "maximum_margin": 2 * max(frequencies) - len(family),
            }
        )
    encoded = json.dumps(document, indent=2, sort_keys=True)
    print(encoded)
    if output:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(encoded + "\n", encoding="utf-8")
    return 1 if satisfiable else 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--width", type=int, default=13)
    parser.add_argument("--cycle-type", default="13")
    parser.add_argument("--allow-nonseparating", action="store_true")
    parser.add_argument("--max-subset-orbits", type=int, default=2_000)
    parser.add_argument("--closure", choices=("lazy", "eager"), default="eager")
    parser.add_argument("--batch", type=int, default=100_000)
    parser.add_argument("--rounds", type=int, default=1_000)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    cycles = parse_cycle_type(args.cycle_type, args.width)
    return solve(
        args.width,
        cycles,
        not args.allow_nonseparating,
        args.max_subset_orbits,
        args.closure,
        args.batch,
        args.rounds,
        args.output,
    )


if __name__ == "__main__":
    raise SystemExit(main())
