//! Deterministic TypeScript declarations for RAD's public host boundary.

use crate::ast::{Decl, Program};
use crate::native_types::NativeTypeFlavor;
use crate::types::{CheckerOutput, Ty};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

pub fn generate(program: &Program, checked: &CheckerOutput) -> Result<String, String> {
    let mut out = String::from(
        "// Generated by `rad types`. Do not edit.\n\n\
         declare const __radBrand: unique symbol;\n\
         export type RadBrand<Name extends string> = { readonly [__radBrand]: Name };\n\
         export type RadEntity = number & RadBrand<\"entity\">;\n\
         export type RadWorldSnapshot = Uint8Array & RadBrand<\"world_snapshot\">;\n\
         export type RadSystem = string & RadBrand<\"system\">;\n\
         export type RadHostHandle<Name extends string> = object & RadBrand<`host:${Name}`>;\n\
         export type Option<T> = { readonly $variant: \"Some\"; readonly value: T } | { readonly $variant: \"None\" };\n\
         export type Result<T, E> = { readonly $variant: \"Ok\"; readonly value: T } | { readonly $variant: \"Err\"; readonly error: E };\n\n",
    );

    let public_native = program
        .declarations
        .iter()
        .filter_map(|decl| match decl {
            Decl::NativeType(native) if native.is_pub => Some(native),
            _ => None,
        })
        .collect::<Vec<_>>();
    let mut public_native = public_native;
    public_native.sort_by(|left, right| left.name.cmp(&right.name));
    for native in public_native {
        let name = ts_name(&native.name);
        match native.flavor {
            NativeTypeFlavor::Scalar => {}
            NativeTypeFlavor::Opaque => {
                writeln!(
                    out,
                    "export type {name} = number & RadBrand<\"{}\">;",
                    native.name
                )
                .unwrap();
            }
            NativeTypeFlavor::Enum => {
                writeln!(out, "export enum {name} {{").unwrap();
                for (member, value) in &native.members {
                    writeln!(out, "  {} = {},", ts_name(member), value).unwrap();
                }
                writeln!(out, "}}\n").unwrap();
            }
            NativeTypeFlavor::Bitflags => {
                writeln!(
                    out,
                    "export type {name} = number & RadBrand<\"{}\">;",
                    native.name
                )
                .unwrap();
                writeln!(out, "export const {name}Flags = {{").unwrap();
                for (member, value) in &native.members {
                    writeln!(out, "  {}: {} as {name},", ts_name(member), value).unwrap();
                }
                writeln!(out, "}} as const;\n").unwrap();
            }
        }
    }

    emit_records(&mut out, "component", &checked.components)?;
    emit_records(&mut out, "resource", &checked.resources)?;
    emit_records(&mut out, "struct", &checked.structs)?;

    let mut sum_types = checked
        .sum_types
        .values()
        .filter(|sum| sum.is_pub)
        .collect::<Vec<_>>();
    sum_types.sort_by(|left, right| left.name.cmp(&right.name));
    for sum in sum_types {
        let generics = generic_decl(&sum.type_params);
        writeln!(out, "export type {}{} =", ts_name(&sum.name), generics).unwrap();
        for (index, variant) in sum.variants.iter().enumerate() {
            let separator = if index + 1 == sum.variants.len() {
                ";"
            } else {
                ""
            };
            write!(out, "  | {{ readonly $variant: \"{}\"", variant.name).unwrap();
            for (field, ty) in &variant.fields {
                write!(
                    out,
                    "; readonly {}: {}",
                    ts_property(field),
                    ty_to_ts(ty, &sum.type_params)?
                )
                .unwrap();
            }
            writeln!(out, " }}{separator}").unwrap();
        }
        out.push('\n');
    }

    let mut state_names = BTreeMap::<String, Vec<String>>::new();
    for decl in &program.declarations {
        if let Decl::State(state) = decl {
            if state.is_pub {
                state_names.insert(
                    state.name.clone(),
                    state
                        .states
                        .iter()
                        .map(|value| value.name.clone())
                        .collect(),
                );
            }
        }
    }
    for (name, states) in state_names {
        let values = states
            .iter()
            .map(|state| format!("\"{state}\""))
            .collect::<Vec<_>>()
            .join(" | ");
        writeln!(out, "export type {} = {};", ts_name(&name), values).unwrap();
    }

    let mut events = checked
        .events
        .values()
        .filter(|event| event.is_pub)
        .collect::<Vec<_>>();
    events.sort_by(|left, right| left.name.cmp(&right.name));
    let mut event_names = Vec::with_capacity(events.len());
    for event in events {
        let name = ts_name(&event.name);
        event_names.push(name.clone());
        writeln!(out, "export interface {name} {{").unwrap();
        writeln!(out, "  readonly $event: \"{}\";", event.name).unwrap();
        for (field, ty) in &event.fields {
            writeln!(
                out,
                "  readonly {}: {};",
                ts_property(field),
                ty_to_ts(ty, &[])?
            )
            .unwrap();
        }
        writeln!(out, "}}\n").unwrap();
    }
    writeln!(
        out,
        "export type RadEvent = {};",
        if event_names.is_empty() {
            "never".to_string()
        } else {
            event_names.join(" | ")
        }
    )
    .unwrap();

    let public_functions = program
        .declarations
        .iter()
        .filter_map(|decl| match decl {
            Decl::Fn(function) if function.is_pub => Some(function.name.clone()),
            _ => None,
        })
        .collect::<BTreeSet<_>>();
    writeln!(out, "\nexport interface RadFunctions {{").unwrap();
    for name in public_functions {
        let signature = checked
            .functions
            .get(&name)
            .ok_or_else(|| format!("checked public function `{name}` has no semantic signature"))?;
        let generics = generic_decl(&signature.type_params);
        write!(out, "  {}{}(", ts_property(&name), generics).unwrap();
        for (index, ty) in signature.params.iter().enumerate() {
            if index > 0 {
                out.push_str(", ");
            }
            write!(out, "arg{index}: {}", ty_to_ts(ty, &signature.type_params)?).unwrap();
        }
        writeln!(
            out,
            "): {};",
            ty_to_ts(&signature.ret, &signature.type_params)?
        )
        .unwrap();
    }
    writeln!(out, "}}\n").unwrap();

    out.push_str(
        "export interface RadTransitionTrace {\n\
           readonly format: \"rad_transition_trace_v1\";\n\
           readonly transition: string;\n\
           readonly before_digest: string;\n\
           readonly after_digest: string;\n\
           readonly changed_components: Readonly<Record<string, number>>;\n\
           readonly events: readonly unknown[];\n\
           readonly writes: readonly unknown[];\n\
           readonly result: unknown;\n\
         }\n\n\
         export interface RadRuntime {\n\
           call<Name extends keyof RadFunctions>(name: Name, ...args: Parameters<RadFunctions[Name]>): ReturnType<RadFunctions[Name]>;\n\
           emit(event: RadEvent): void;\n\
           exportSnapshot(): RadWorldSnapshot;\n\
           importSnapshot(snapshot: RadWorldSnapshot): void;\n\
           executeTransition<Name extends keyof RadFunctions>(name: Name, ...args: Parameters<RadFunctions[Name]>): RadTransitionTrace;\n\
         }\n",
    );
    Ok(out)
}

trait PublicRecord {
    fn name(&self) -> &str;
    fn is_pub(&self) -> bool;
    fn fields(&self) -> &[(String, Ty)];
}

impl PublicRecord for crate::types::ComponentType {
    fn name(&self) -> &str {
        &self.name
    }
    fn is_pub(&self) -> bool {
        self.is_pub
    }
    fn fields(&self) -> &[(String, Ty)] {
        &self.fields
    }
}

impl PublicRecord for crate::types::ResourceType {
    fn name(&self) -> &str {
        &self.name
    }
    fn is_pub(&self) -> bool {
        self.is_pub
    }
    fn fields(&self) -> &[(String, Ty)] {
        &self.fields
    }
}

impl PublicRecord for crate::types::StructType {
    fn name(&self) -> &str {
        &self.name
    }
    fn is_pub(&self) -> bool {
        self.is_pub
    }
    fn fields(&self) -> &[(String, Ty)] {
        &self.fields
    }
}

fn emit_records<T: PublicRecord>(
    out: &mut String,
    kind: &str,
    records: &std::collections::HashMap<String, T>,
) -> Result<(), String> {
    let mut records = records
        .values()
        .filter(|record| record.is_pub())
        .collect::<Vec<_>>();
    records.sort_by(|left, right| left.name().cmp(right.name()));
    for record in records {
        writeln!(out, "/** RAD {kind}. */").unwrap();
        writeln!(out, "export interface {} {{", ts_name(record.name())).unwrap();
        if kind == "component" {
            writeln!(out, "  readonly $component: \"{}\";", record.name()).unwrap();
        }
        for (field, ty) in record.fields() {
            writeln!(
                out,
                "  readonly {}: {};",
                ts_property(field),
                ty_to_ts(ty, &[])?
            )
            .unwrap();
        }
        writeln!(out, "}}\n").unwrap();
    }
    Ok(())
}

fn generic_decl(names: &[String]) -> String {
    if names.is_empty() {
        String::new()
    } else {
        format!(
            "<{}>",
            names
                .iter()
                .map(|name| ts_name(name))
                .collect::<Vec<_>>()
                .join(", ")
        )
    }
}

fn ty_to_ts(ty: &Ty, type_params: &[String]) -> Result<String, String> {
    Ok(match ty {
        Ty::Int | Ty::Float => "number".to_string(),
        Ty::Native { name, .. } => ts_name(name),
        Ty::Str => "string".to_string(),
        Ty::Bool => "boolean".to_string(),
        Ty::Nil => "null".to_string(),
        Ty::List(inner) => format!(
            "readonly {}[]",
            parenthesize(&ty_to_ts(inner, type_params)?)
        ),
        Ty::Tuple(items) => format!(
            "readonly [{}]",
            items
                .iter()
                .map(|item| ty_to_ts(item, type_params))
                .collect::<Result<Vec<_>, _>>()?
                .join(", ")
        ),
        Ty::Map(key, value) => format!(
            "ReadonlyMap<{}, {}>",
            ty_to_ts(key, type_params)?,
            ty_to_ts(value, type_params)?
        ),
        Ty::Component(name)
        | Ty::Struct(name)
        | Ty::State(name)
        | Ty::SumType(name)
        | Ty::Event(name) => ts_name(name),
        Ty::Fn { params, ret, .. } => format!(
            "({}) => {}",
            params
                .iter()
                .enumerate()
                .map(|(index, ty)| Ok(format!("arg{index}: {}", ty_to_ts(ty, type_params)?)))
                .collect::<Result<Vec<_>, String>>()?
                .join(", "),
            ty_to_ts(ret, type_params)?
        ),
        Ty::Task(inner) => format!("Promise<{}>", ty_to_ts(inner, type_params)?),
        Ty::EntityId => "RadEntity".to_string(),
        Ty::BitSet => "ReadonlySet<number>".to_string(),
        Ty::WorldFork => "RadWorldSnapshot".to_string(),
        Ty::SystemRef => "RadSystem".to_string(),
        Ty::Any => "unknown".to_string(),
        Ty::Void => "void".to_string(),
        Ty::Union(items) => items
            .iter()
            .map(|item| ty_to_ts(item, type_params))
            .collect::<Result<Vec<_>, _>>()?
            .join(" | "),
        Ty::Var(index) => type_params
            .get(*index as usize)
            .map(|name| ts_name(name))
            .ok_or_else(|| format!("unresolved generic type variable T{index}"))?,
        Ty::App(name, args) => format!(
            "{}<{}>",
            ts_name(name),
            args.iter()
                .map(|arg| ty_to_ts(arg, type_params))
                .collect::<Result<Vec<_>, _>>()?
                .join(", ")
        ),
    })
}

fn parenthesize(value: &str) -> String {
    if value.contains(" | ") || value.contains(" => ") {
        format!("({value})")
    } else {
        value.to_string()
    }
}

fn ts_name(name: &str) -> String {
    name.replace("::", "_").replace('-', "_")
}

fn ts_property(name: &str) -> String {
    let valid = name.chars().enumerate().all(|(index, ch)| {
        ch == '_' || ch == '$' || ch.is_ascii_alphabetic() || ch.is_ascii_digit() && index > 0
    });
    if valid {
        name.to_string()
    } else {
        serde_json::to_string(name).expect("serializing a property name cannot fail")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn public_semantic_surface_generates_deterministic_nominal_types() {
        let source = r#"
            pub opaque type ManagerGid = u32
            pub enum Lifecycle: u8 { Live = 1, Retired = 2 }
            pub bitflags Publication: u32 { Named = 1, Ready = 2 }
            pub component Identity { manager: ManagerGid = ManagerGid(u32(0)) }
            pub resource Clock { tick: u64 = u64(0) }
            pub event Published { target: entity }
            pub fn find(manager: ManagerGid) -> Option<entity> { return None }
        "#;
        let parsed = crate::pipeline::parse_source(source, crate::parser::ParserOptions);
        assert!(
            parsed.lexer_errors.is_empty(),
            "lex errors: {:?}",
            parsed.lexer_errors
        );
        assert!(
            parsed.parser_errors.is_empty(),
            "parse errors: {:?}",
            parsed.parser_errors
        );
        let analysis = crate::pipeline::analyze_program(
            &parsed.program,
            &std::collections::HashMap::new(),
            crate::checker::CheckerOptions::default(),
        );
        assert!(
            analysis.errors().is_empty(),
            "check errors: {:?}",
            analysis.errors()
        );

        let first = generate(&parsed.program, analysis.output()).unwrap();
        let second = generate(&parsed.program, analysis.output()).unwrap();
        assert_eq!(first, second);
        assert!(first.contains("export type ManagerGid = number & RadBrand<\"ManagerGid\">;"));
        assert!(first.contains("export enum Lifecycle"));
        assert!(first.contains("export const PublicationFlags"));
        assert!(first.contains("export interface Identity"));
        assert!(first.contains("export interface Clock"));
        assert!(first.contains("readonly $event: \"Published\""));
        assert!(first.contains("find(arg0: ManagerGid): Option<RadEntity>;"));
        assert!(first.contains("executeTransition<Name extends keyof RadFunctions>"));
    }
}
