use std::fmt::Write as _;
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let output = std::env::args_os()
        .nth(1)
        .map(PathBuf::from)
        .ok_or("usage: generate_builtin_reference <output.md>")?;
    let entries = rad_vm::builtins::builtin_api_catalog();
    let mut markdown = String::from(
        "<!-- Generated by core/vm/examples/generate_builtin_reference.rs. Do not edit. -->\n\
         # Complete builtin API catalog\n\n\
         This page is generated from the runtime-owned builtin catalog and type/effect tables. \
         Every runtime builtin appears exactly once. Detailed behavior and examples are linked from \
         the [curated builtin guide](../builtins.md).\n\n\
         Error contract: invalid arity, type, range, capability, or platform state is a typed RAD runtime \
         error unless the signature returns `Option` or `Result`. Complexity is defined by the curated \
         category tables; no unlisted operation carries a constant-time guarantee.\n\n",
    );
    for entry in entries {
        writeln!(markdown, "<a id=\"{}\"></a>", entry.name)?;
        writeln!(markdown, "## `{}`\n", entry.name)?;
        writeln!(markdown, "```text\n{}\n```\n", entry.signature)?;
        writeln!(markdown, "- Category: `{}`", entry.category)?;
        writeln!(markdown, "- Arity: `{}` argument(s)", entry.arity)?;
        writeln!(markdown, "- Effects: `{}`", entry.effects)?;
        writeln!(
            markdown,
            "- Purity: `{}`",
            if entry.pure {
                "pure"
            } else {
                "effectful or readonly"
            }
        )?;
        if !entry.type_parameters.is_empty() {
            writeln!(
                markdown,
                "- Type parameters: `{}`",
                entry.type_parameters.join(", ")
            )?;
        }
        writeln!(markdown, "- Errors: {}", entry.errors)?;
        writeln!(markdown, "- Determinism: {}", entry.determinism)?;
        writeln!(markdown, "- Complexity: `{}`", entry.complexity)?;
        writeln!(markdown, "- Allocation: {}", entry.allocation)?;
        writeln!(markdown, "- Native: `{}`", entry.native)?;
        writeln!(markdown, "- WASM: `{}`", entry.wasm)?;
        writeln!(markdown, "- Sandbox: `{}`", entry.sandbox)?;
        writeln!(markdown, "- Transaction body: `{}`", entry.transaction)?;
        writeln!(markdown, "- Post-commit: `{}`", entry.post_commit)?;
        writeln!(markdown, "- Settlement: `{}`", entry.settlement)?;
        writeln!(markdown)?;
    }
    if let Some(parent) = output.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(output, markdown)?;
    Ok(())
}
