import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.dirname(fileURLToPath(import.meta.url));
const contractPath = path.join(root, 'contract.json');
const radPath = path.join(root, '..', 'server', 'src', 'generated', 'match_protocol.rad');
const tsPath = path.join(root, '..', 'client', 'src', 'generated', 'matchProtocol.ts');
const checkOnly = process.argv.includes('--check');
const contract = JSON.parse(await readFile(contractPath, 'utf8'));

function snake(name) {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').replace(/[^A-Za-z0-9]+/g, '_').toLowerCase();
}

function screaming(name) {
  return snake(name).toUpperCase();
}

function quoted(value) {
  return JSON.stringify(value);
}

function validateCodeTable(name, rows) {
  const names = new Set();
  const codes = new Set();
  for (const row of rows) {
    if (!row.name || !Number.isInteger(row.code) || row.code <= 0 || row.code > 255) {
      throw new Error(`${name} has an invalid row`);
    }
    if (names.has(row.name)) throw new Error(`${name} repeats name ${row.name}`);
    names.add(row.name);
    if (codes.has(row.code)) throw new Error(`${name} repeats code ${row.code}`);
    codes.add(row.code);
    for (const alias of row.aliases ?? []) {
      if (names.has(alias)) throw new Error(`${name} repeats alias ${alias}`);
      names.add(alias);
    }
  }
}

function validateContract(value) {
  if (value.endianness !== 'little') throw new Error('only little-endian contracts are supported');
  if (!Number.isInteger(value.version) || value.version <= 0 || value.version > 255) {
    throw new Error('protocol version must fit u8');
  }
  if (!Number.isInteger(value.header?.magic) || value.header.magic < 0 || value.header.magic > 255) {
    throw new Error('protocol magic must fit u8');
  }
  const kinds = new Set();
  for (const [packetName, packet] of Object.entries(value.packets)) {
    if (!Number.isInteger(packet.kind) || packet.kind <= 0 || packet.kind > 255) {
      throw new Error(`${packetName} kind must fit nonzero u8`);
    }
    if (kinds.has(packet.kind)) throw new Error(`packet kind ${packet.kind} repeats`);
    kinds.add(packet.kind);
    const bytes = packet.bytes ?? packet.headerBytes;
    if (!Number.isInteger(bytes) || bytes < value.header.bytes) {
      throw new Error(`${packetName} has an invalid size`);
    }
    for (const [field, offset] of Object.entries(packet.fields ?? {})) {
      if (!Number.isInteger(offset) || offset < 0 || offset >= bytes) {
        throw new Error(`${packetName}.${field} has an invalid offset`);
      }
    }
    for (const [recordName, record] of Object.entries(packet.records ?? {})) {
      if (!Number.isInteger(record.bytes) || record.bytes <= 0) {
        throw new Error(`${packetName}.${recordName} has an invalid size`);
      }
      for (const [field, offset] of Object.entries(record.fields ?? {})) {
        if (!Number.isInteger(offset) || offset < 0 || offset >= record.bytes) {
          throw new Error(`${packetName}.${recordName}.${field} has an invalid offset`);
        }
      }
    }
  }
  validateCodeTable('statuses', value.statuses);
  validateCodeTable('correctionReasons', value.correctionReasons);
  validateCodeTable('avatarModels', value.avatarModels);
  validateCodeTable('projectileImpactReasons', value.projectileImpactReasons);
}

function radFunction(name, value, type = 'int') {
  const literal = type === 'str' ? quoted(value) : type === 'float' ? `${value}.0` : value;
  return `pub fn ${name}() -> ${type} { return ${literal} }`;
}

function generateRad(value) {
  const lines = [
    '// @generated by protocol/generate.mjs from protocol/contract.json.',
    '// Do not edit this file directly.',
    '',
    radFunction('match_protocol_name', value.name, 'str'),
    radFunction('protocol_magic', value.header.magic),
    radFunction('protocol_version', value.version),
    radFunction('coord_scale', value.coordinateScale, 'float'),
    radFunction('protocol_header_len', value.header.bytes),
  ];
  for (const [field, offset] of Object.entries(value.header.fields)) {
    lines.push(radFunction(`header_${snake(field)}_offset`, offset));
  }
  for (const [packetName, packet] of Object.entries(value.packets)) {
    lines.push(radFunction(`packet_kind_${snake(packetName)}`, packet.kind));
    if (packet.bytes !== undefined) lines.push(radFunction(`${snake(packetName)}_packet_len`, packet.bytes));
    if (packet.headerBytes !== undefined) lines.push(radFunction(`${snake(packetName)}_packet_header_len`, packet.headerBytes));
    for (const [field, offset] of Object.entries(packet.fields ?? {})) {
      lines.push(radFunction(`${snake(packetName)}_${snake(field)}_offset`, offset));
    }
    for (const [recordName, record] of Object.entries(packet.records ?? {})) {
      const recordPrefix = `${snake(packetName)}_${snake(recordName)}_record`;
      lines.push(radFunction(`${recordPrefix}_len`, record.bytes));
      for (const [field, offset] of Object.entries(record.fields ?? {})) {
        lines.push(radFunction(`${recordPrefix}_${snake(field)}_offset`, offset));
      }
    }
  }
  lines.push(
    'pub fn state_packet_len() -> int { return state_packet_header_len() + state_avatar_record_len() }',
    '',
    ...radEncoder('status_code', value.statuses, 0),
    '',
    ...radEncoder('correction_reason_code', value.correctionReasons, 0),
    '',
    ...radEncoder('avatar_model_code', value.avatarModels, 0),
  );
  for (const row of value.projectileImpactReasons) {
    lines.push(radFunction(`projectile_impact_reason_${snake(row.name)}`, row.code));
  }
  return `${lines.join('\n')}\n`;
}

function radEncoder(name, rows, fallback) {
  const argument = name === 'avatar_model_code' ? 'model' : 'status';
  const lines = [`pub fn ${name}(${argument}: str) -> int {`];
  for (const row of rows) {
    const names = [row.name, ...(row.aliases ?? [])];
    lines.push(`    if ${names.map((item) => `${argument} == ${quoted(item)}`).join(' or ')} { return ${row.code} }`);
  }
  lines.push(`    return ${fallback}`, '}');
  return lines;
}

function generateTs(value) {
  const lines = [
    '// @generated by protocol/generate.mjs from protocol/contract.json.',
    '// Do not edit this file directly.',
    '',
    `export const MATCH_PROTOCOL_NAME = ${quoted(value.name)};`,
    `export const PROTOCOL_MAGIC = ${value.header.magic};`,
    `export const PROTOCOL_VERSION = ${value.version};`,
    `export const COORD_SCALE = ${value.coordinateScale};`,
    `export const PROTOCOL_HEADER_BYTES = ${value.header.bytes};`,
  ];
  for (const [field, offset] of Object.entries(value.header.fields)) {
    lines.push(`export const HEADER_${screaming(field)}_OFFSET = ${offset};`);
  }
  for (const [packetName, packetDefinition] of Object.entries(value.packets)) {
    const packet = screaming(packetName);
    lines.push(`export const PACKET_KIND_${packet} = ${packetDefinition.kind};`);
    if (packetDefinition.bytes !== undefined) {
      lines.push(`export const ${packet}_PACKET_BYTES = ${packetDefinition.bytes};`);
    }
    if (packetDefinition.headerBytes !== undefined) {
      lines.push(`export const ${packet}_PACKET_HEADER_BYTES = ${packetDefinition.headerBytes};`);
    }
    for (const [field, offset] of Object.entries(packetDefinition.fields ?? {})) {
      lines.push(`export const ${packet}_${screaming(field)}_OFFSET = ${offset};`);
    }
    for (const [recordName, record] of Object.entries(packetDefinition.records ?? {})) {
      const recordPrefix = `${packet}_${screaming(recordName)}_RECORD`;
      lines.push(`export const ${recordPrefix}_BYTES = ${record.bytes};`);
      for (const [field, offset] of Object.entries(record.fields ?? {})) {
        lines.push(`export const ${recordPrefix}_${screaming(field)}_OFFSET = ${offset};`);
      }
    }
  }
  lines.push(
    'export const STATE_PACKET_BYTES = STATE_PACKET_HEADER_BYTES + STATE_AVATAR_RECORD_BYTES;',
    '',
    ...tsDecoder('statusFromCode', value.statuses, 'unknown'),
    '',
    ...tsDecoder('correctionReasonFromCode', value.correctionReasons, 'none'),
    '',
    ...tsDecoder('modelFromCode', value.avatarModels, value.avatarModels[0].name),
    '',
    ...tsDecoder('projectileImpactReasonFromCode', value.projectileImpactReasons, 'unknown'),
  );
  return `${lines.join('\n')}\n`;
}

function tsDecoder(name, rows, fallback) {
  const lines = [`export function ${name}(code: number): string {`, '  switch (code) {'];
  for (const row of rows) lines.push(`    case ${row.code}: return ${quoted(row.name)};`);
  lines.push(`    default: return ${quoted(fallback)};`, '  }', '}');
  return lines;
}

async function adopt(file, expected) {
  if (checkOnly) {
    const actual = await readFile(file, 'utf8').catch(() => '');
    if (actual !== expected) throw new Error(`${path.relative(root, file)} is stale; run node protocol/generate.mjs`);
  } else {
    await writeFile(file, expected, 'utf8');
  }
}

validateContract(contract);
const radSource = generateRad(contract);
const tsSource = generateTs(contract);
assertUniqueBindings('RAD', radSource, /^pub fn ([A-Za-z_][A-Za-z0-9_]*)/gm);
assertUniqueBindings('TypeScript', tsSource, /^export (?:const|function) ([A-Za-z_][A-Za-z0-9_]*)/gm);
await adopt(radPath, radSource);
await adopt(tsPath, tsSource);

function assertUniqueBindings(target, source, pattern) {
  const seen = new Set();
  for (const match of source.matchAll(pattern)) {
    const name = match[1];
    if (seen.has(name)) throw new Error(`${target} binding ${name} is generated more than once`);
    seen.add(name);
  }
}
