"""Construct a local polynomial NS time jet. Generated data is not trusted by RAD."""
import json
from pathlib import Path
import sympy as s

x, y, z = s.symbols("x y z")
coordinates = (x, y, z)
position = s.Matrix(coordinates)
A = s.diag(1, 2, -3)
q = position.dot(position)


def curl(v):
    return s.Matrix([s.diff(v[2], y)-s.diff(v[1], z),
                     s.diff(v[0], z)-s.diff(v[2], x),
                     s.diff(v[1], x)-s.diff(v[0], y)])


def divergence(v):
    return s.expand(sum(s.diff(v[i], coordinates[i]) for i in range(3)))


def laplacian(p):
    return s.expand(sum(s.diff(p, v, 2) for v in coordinates))


def inverse_laplacian(p):
    # Finite right inverse: sum (-1)^k I_x^(2k+2) (d_yy+d_zz)^k.
    result, term, k = s.Integer(0), s.expand(p), 0
    while term != 0:
        integrated = term
        for _ in range(2*k+2):
            integrated = s.integrate(integrated, x)
        result += (-1)**k*integrated
        term = s.expand(s.diff(term, y, 2)+s.diff(term, z, 2))
        k += 1
    result = s.expand(result)
    assert s.expand(laplacian(result)-p) == 0
    return result


def advect(v, w):
    return (w.jacobian(position)*v).applyfunc(s.expand)


def construct(nu):
    v = curl(-(1-q)*position.cross(A*position)/3).applyfunc(s.expand)
    n0 = advect(v, v)
    p0 = inverse_laplacian(-divergence(n0))
    v1 = (nu*v.applyfunc(laplacian)-n0-s.Matrix([s.diff(p0, c) for c in coordinates])).applyfunc(s.expand)
    n1 = advect(v, v1)+advect(v1, v)
    p1 = inverse_laplacian(-divergence(n1))
    v2 = ((nu*v1.applyfunc(laplacian)-n1-s.Matrix([s.diff(p1, c) for c in coordinates]))/2).applyfunc(s.expand)
    n2 = advect(v, v2)+advect(v1, v1)+advect(v2, v)
    p2 = inverse_laplacian(-divergence(n2))
    v3 = ((nu*v2.applyfunc(laplacian)-n2-s.Matrix([s.diff(p2, c) for c in coordinates]))/3).applyfunc(s.expand)
    assert divergence(v) == divergence(v1) == divergence(v2) == divergence(v3) == 0
    fields = list(v)+list(v1)+list(v2)+[p0, p1]+list(v3)+[p2]
    scales, terms = [], []
    for field in fields:
        poly = s.Poly(field, coordinates)
        scale = int(s.ilcm(1, *[coefficient.q for coefficient in poly.coeffs()]))
        scales.append(scale)
        terms.append([[144*i+12*j+k, int(coefficient*scale)]
                      for (i, j, k), coefficient in poly.terms() if coefficient != 0])
    return dict(nu=nu, monomial_base=12, scales=scales, terms=terms)


def main():
    cases = [construct(nu) for nu in [1, 2]]
    destination = Path(__file__).with_name("coupled_jet_data.json")
    destination.write_text(json.dumps(cases, indent=2)+"\n", encoding="utf-8")
    # A sparse data module: the independent RAD checker verifies all PDE
    # coefficients and never calls the symbolic construction above.
    lines = ['// Generated by build_coupled_jet.py. Data is checked by coupled_evolution.rad.',
             'use "poly11.rad"',
             'pub pure fn jet_field(nu: int, field: int) -> list<int> {',
             '    assert(nu == 1 or nu == 2, "jet viscosity domain")',
             '    assert(field >= 0 and field < 15, "jet field domain")']
    u3_scale = int(s.ilcm(*[case['scales'][i] for case in cases for i in [11, 12, 13]]))
    p2_scale = int(s.ilcm(*[case['scales'][14] for case in cases]))
    common = [3]*3+[45]*3+[405]*3+[135, 810]+[u3_scale]*3+[p2_scale]
    print('common field scales', common)
    for case in cases:
        lines.append(f'    if nu == {case["nu"]} {{')
        for i, terms in enumerate(case['terms']):
            factor = common[i]//case['scales'][i]
            assert factor*case['scales'][i] == common[i]
            sparse = [[slot, value*factor] for slot, value in terms]
            lines.append(f'        if field == {i} {{ return from_terms({json.dumps(sparse)}) }}')
        lines.append('    }')
    lines += ['    assert(false, "missing jet data")', '    return zero_poly()', '}']
    destination.with_name('coupled_jet_data.rad').write_text('\n'.join(lines)+'\n', encoding='utf-8')
    for case in cases:
        print("nu", case["nu"], "scales", case["scales"], "largest numerator",
              max(abs(term[1]) for field in case["terms"] for term in field))


if __name__ == "__main__":
    main()
