//! Dense project-owned kernels for finite Boolean-lattice workloads.
//!
//! These operations are intentionally domain-general: bit masks represent
//! finite sets, bitwise OR is their join, and `or_closure` computes the finite
//! join-semilattice generated by a list of masks.  Keeping the tight closure
//! and audit loops here avoids millions of interpreter dispatches without
//! baking search-specific scoring into the RAD VM.

use std::collections::HashSet;

const DENSE_MAX_MASK: u64 = (1 << 20) - 1;
const MAX_CLOSURE_MEMBERS: usize = 1 << 20;
const MAX_TRANSFORM_WIDTH: usize = 20;
// Keep the finite-lattice model, deletion transition, and exchange search as
// distinct responsibilities while sharing the private mask primitives above.
include!("boolean_lattice/lattice.rs");
include!("boolean_lattice/deletion.rs");
include!("boolean_lattice/exchange.rs");
include!("boolean_lattice/tests.rs");
