//! Dense project-owned kernels for finite Boolean-lattice workloads.
//!
//! These operations are intentionally domain-general: bit masks represent
//! finite sets, bitwise OR is their join, and `or_closure` computes the finite
//! join-semilattice generated by a list of masks.  Keeping the tight closure
//! and audit loops here avoids millions of interpreter dispatches without
//! baking search-specific scoring into the RAD VM.

use std::collections::HashSet;

const DENSE_MAX_MASK: u64 = (1 << 20) - 1;
const MAX_CLOSURE_MEMBERS: usize = 1 << 20;
const MAX_TRANSFORM_WIDTH: usize = 20;

fn checked_masks(values: &[i64], operation: &str) -> Result<Vec<u64>, String> {
    values
        .iter()
        .map(|value| {
            u64::try_from(*value)
                .map_err(|_| format!("{operation} expects non-negative integer masks, got {value}"))
        })
        .collect()
}

fn push_member(family: &mut Vec<u64>, member: u64, inserted: bool) -> Result<(), String> {
    if !inserted {
        return Ok(());
    }
    if family.len() >= MAX_CLOSURE_MEMBERS {
        return Err(format!(
            "or_closure exceeds the {MAX_CLOSURE_MEMBERS}-member safety limit"
        ));
    }
    family.push(member);
    Ok(())
}

fn or_closure_masks(generators: &[i64]) -> Result<Vec<u64>, String> {
    let mut generators = checked_masks(generators, "or_closure")?;
    // Sparse generators expose the smallest basis early. Once a generator is
    // already in the partial closure, adjoining it is a mathematical no-op;
    // skipping that pass is decisive for overcomplete bases used by search.
    generators.sort_unstable_by_key(|value| (value.count_ones(), *value));
    generators.dedup();
    let maximum = generators.iter().fold(0u64, |joined, value| joined | value);
    let mut family = vec![0u64];

    if maximum <= DENSE_MAX_MASK {
        let mut present = vec![0u64; maximum as usize / 64 + 1];
        present[0] = 1;
        for generator in generators {
            let generator_word = generator as usize / 64;
            let generator_mask = 1u64 << (generator % 64);
            if present[generator_word] & generator_mask != 0 {
                continue;
            }
            let before = family.len();
            for index in 0..before {
                let joined = family[index] | generator;
                let word = joined as usize / 64;
                let mask = 1u64 << (joined % 64);
                let inserted = present[word] & mask == 0;
                if inserted {
                    present[word] |= mask;
                }
                push_member(&mut family, joined, inserted)?;
            }
        }
    } else {
        let mut present = HashSet::from([0u64]);
        for generator in generators {
            if present.contains(&generator) {
                continue;
            }
            let before = family.len();
            for index in 0..before {
                let joined = family[index] | generator;
                let inserted = present.insert(joined);
                push_member(&mut family, joined, inserted)?;
            }
        }
    }

    family.sort_unstable();
    Ok(family)
}

/// Return the smallest family containing `0` and every generator and closed
/// under bitwise OR.  Output is sorted and duplicate-free.
pub(crate) fn or_closure(generators: &[i64]) -> Result<Vec<i64>, String> {
    or_closure_masks(generators)?
        .into_iter()
        .map(|value| {
            i64::try_from(value)
                .map_err(|_| "or_closure result exceeds RAD's signed integer range".to_string())
        })
        .collect()
}

fn checked_width(width: i64, operation: &str) -> Result<usize, String> {
    let width = usize::try_from(width)
        .ok()
        .filter(|width| *width <= 63)
        .ok_or_else(|| format!("{operation} width must be between 0 and 63"))?;
    Ok(width)
}

fn bit_frequencies_masks(
    values: &[u64],
    width: usize,
    operation: &str,
) -> Result<Vec<i64>, String> {
    let outside_mask = if width == 63 {
        1u64 << 63
    } else {
        !0u64 << width
    };
    let mut frequencies = vec![0i64; width];
    for value in values {
        if value & outside_mask != 0 {
            return Err(format!(
                "{operation} mask {value} has a bit outside width {width}"
            ));
        }
        for (bit, count) in frequencies.iter_mut().enumerate() {
            *count += ((value >> bit) & 1) as i64;
        }
    }
    Ok(frequencies)
}

/// Count the occurrence of each bit in a list of masks.
pub(crate) fn bit_frequencies(values: &[i64], width: i64) -> Result<Vec<i64>, String> {
    let width = checked_width(width, "bit_frequencies")?;
    let values = checked_masks(values, "bit_frequencies")?;
    bit_frequencies_masks(&values, width, "bit_frequencies")
}

/// Compute closure cardinality and bit frequencies without materializing the
/// complete family as VM values. This is the compact hot path for search and
/// dataflow analyses that only need aggregate lattice statistics.
pub(crate) fn or_closure_stats(
    generators: &[i64],
    width: i64,
) -> Result<(i64, Vec<i64>, bool, i64), String> {
    let width = checked_width(width, "or_closure_stats")?;
    let family = or_closure_masks(generators)?;
    let frequencies = bit_frequencies_masks(&family, width, "or_closure_stats")?;
    let separating = (0..width).all(|left| {
        ((left + 1)..width).all(|right| {
            family
                .iter()
                .any(|member| ((member >> left) & 1) != ((member >> right) & 1))
        })
    });
    let size = i64::try_from(family.len())
        .map_err(|_| "or_closure_stats result exceeds RAD's integer range".to_string())?;
    let mut digest = blake3::Hasher::new();
    digest.update(b"rad-or-closure/v1\0");
    for member in &family {
        digest.update(&member.to_le_bytes());
    }
    let digest = digest.finalize();
    let mut prefix = [0u8; 8];
    prefix.copy_from_slice(&digest.as_bytes()[..8]);
    let signature = (u64::from_le_bytes(prefix) & i64::MAX as u64) as i64;
    Ok((size, frequencies, separating, signature))
}

/// Test whether a duplicate-free family is closed under bitwise OR.
pub(crate) fn is_or_closed(values: &[i64]) -> Result<bool, String> {
    let values = checked_masks(values, "is_or_closed")?;
    if values.len() > MAX_CLOSURE_MEMBERS {
        return Err(format!(
            "is_or_closed exceeds the {MAX_CLOSURE_MEMBERS}-member safety limit"
        ));
    }
    let maximum = values.iter().copied().max().unwrap_or(0);

    if maximum <= DENSE_MAX_MASK {
        let mut present = vec![false; maximum as usize + 1];
        for value in &values {
            let slot = &mut present[*value as usize];
            if *slot {
                return Ok(false);
            }
            *slot = true;
        }
        for left in &values {
            for right in &values {
                let joined = left | right;
                if joined > maximum || !present[joined as usize] {
                    return Ok(false);
                }
            }
        }
    } else {
        let present = values.iter().copied().collect::<HashSet<_>>();
        if present.len() != values.len() {
            return Ok(false);
        }
        for left in &values {
            for right in &values {
                if !present.contains(&(left | right)) {
                    return Ok(false);
                }
            }
        }
    }
    Ok(true)
}

/// Count ordered pairs `(A, B)` in `family` whose union is absent.
///
/// A direct audit is quadratic in the family size.  On a Boolean cube the OR
/// zeta transform counts every possible union in `O(width * 2^width)`: zeta
/// transform the membership indicator, square pointwise, then Mobius invert.
/// The result is exact and is useful for measuring *distance* from closure,
/// rather than returning only a boolean verdict.
pub(crate) fn or_violation_count(values: &[i64], width: i64) -> Result<i64, String> {
    let width = usize::try_from(width)
        .ok()
        .filter(|width| *width <= MAX_TRANSFORM_WIDTH)
        .ok_or_else(|| {
            format!("or_violation_count width must be between 0 and {MAX_TRANSFORM_WIDTH}")
        })?;
    let values = checked_masks(values, "or_violation_count")?;
    let cube_size = 1usize << width;
    let mut present = vec![false; cube_size];
    let mut subset_counts = vec![0i64; cube_size];
    for value in values {
        let index = usize::try_from(value)
            .ok()
            .filter(|index| *index < cube_size)
            .ok_or_else(|| {
                format!("or_violation_count mask {value} has a bit outside width {width}")
            })?;
        if std::mem::replace(&mut present[index], true) {
            return Err(format!(
                "or_violation_count expects a duplicate-free family; mask {value} repeats"
            ));
        }
        subset_counts[index] = 1;
    }

    for bit in 0..width {
        for mask in 0..cube_size {
            if mask & (1usize << bit) != 0 {
                subset_counts[mask] += subset_counts[mask ^ (1usize << bit)];
            }
        }
    }
    for count in &mut subset_counts {
        *count = count
            .checked_mul(*count)
            .ok_or_else(|| "or_violation_count pair count overflow".to_string())?;
    }
    for bit in 0..width {
        for mask in 0..cube_size {
            if mask & (1usize << bit) != 0 {
                subset_counts[mask] -= subset_counts[mask ^ (1usize << bit)];
            }
        }
    }

    let mut violations = 0i64;
    for (mask, count) in subset_counts.into_iter().enumerate() {
        if !present[mask] {
            violations = violations
                .checked_add(count)
                .ok_or_else(|| "or_violation_count result overflow".to_string())?;
        }
    }
    Ok(violations)
}

/// Return the members that can be removed while preserving OR closure.
///
/// For a member `U`, every pair involving `U` disappears when `U` is
/// removed.  If `q(U)` family members are subsets of `U`, those account for
/// exactly `2*q(U)-1` ordered pairs with union `U`.  Removal is legal exactly
/// when there are no additional pairs of proper remaining parents.  Both
/// `q(U)` and the exact-union pair counts come from one OR zeta/Mobius pass.
pub(crate) fn or_deletable_members(values: &[i64], width: i64) -> Result<Vec<i64>, String> {
    let width = usize::try_from(width)
        .ok()
        .filter(|width| *width <= MAX_TRANSFORM_WIDTH)
        .ok_or_else(|| {
            format!("or_deletable_members width must be between 0 and {MAX_TRANSFORM_WIDTH}")
        })?;
    let values = checked_masks(values, "or_deletable_members")?;
    let cube_size = 1usize << width;
    let mut present = vec![false; cube_size];
    let mut subset_counts = vec![0i64; cube_size];
    for value in values {
        let index = usize::try_from(value)
            .ok()
            .filter(|index| *index < cube_size)
            .ok_or_else(|| {
                format!("or_deletable_members mask {value} has a bit outside width {width}")
            })?;
        if std::mem::replace(&mut present[index], true) {
            return Err(format!(
                "or_deletable_members expects a duplicate-free family; mask {value} repeats"
            ));
        }
        subset_counts[index] = 1;
    }

    for bit in 0..width {
        for mask in 0..cube_size {
            if mask & (1usize << bit) != 0 {
                subset_counts[mask] += subset_counts[mask ^ (1usize << bit)];
            }
        }
    }
    let mut union_counts = subset_counts
        .iter()
        .map(|count| {
            count
                .checked_mul(*count)
                .ok_or_else(|| "or_deletable_members pair count overflow".to_string())
        })
        .collect::<Result<Vec<_>, _>>()?;
    for bit in 0..width {
        for mask in 0..cube_size {
            if mask & (1usize << bit) != 0 {
                union_counts[mask] -= union_counts[mask ^ (1usize << bit)];
            }
        }
    }

    if union_counts
        .iter()
        .enumerate()
        .any(|(mask, count)| !present[mask] && *count != 0)
    {
        return Err("or_deletable_members expects an OR-closed family".to_string());
    }

    Ok(present
        .iter()
        .enumerate()
        .filter_map(|(mask, is_present)| {
            if !is_present {
                return None;
            }
            let pairs_removed_with_member = 2 * subset_counts[mask] - 1;
            (union_counts[mask] == pairs_removed_with_member).then_some(mask as i64)
        })
        .collect::<Vec<_>>())
}

pub(crate) struct OrDeletionState {
    pub family_size: i64,
    pub family_frequencies: Vec<i64>,
    pub deletion_surpluses: Vec<i64>,
    pub deletable_members: Vec<i64>,
    pub effective_deletable_members: Vec<i64>,
    pub separating: bool,
}

/// Analyze the OR-closed complement of a sparse deletion list.
///
/// This is the COW-friendly form of [`or_deletable_members`]: speculative
/// worlds retain only their deletion path, while the dense Boolean cube stays
/// inside one native transform instead of becoming thousands of VM values per
/// fork.
pub(crate) fn or_deletion_state(deleted: &[i64], width: i64) -> Result<OrDeletionState, String> {
    let width = usize::try_from(width)
        .ok()
        .filter(|width| *width <= MAX_TRANSFORM_WIDTH)
        .ok_or_else(|| {
            format!("or_deletion_state width must be between 0 and {MAX_TRANSFORM_WIDTH}")
        })?;
    let deleted = checked_masks(deleted, "or_deletion_state")?;
    let cube_size = 1usize << width;
    let mut family_present = vec![true; cube_size];
    let mut deleted_frequencies = vec![0i64; width];
    for value in deleted {
        let index = usize::try_from(value)
            .ok()
            .filter(|index| *index < cube_size)
            .ok_or_else(|| {
                format!("or_deletion_state mask {value} has a bit outside width {width}")
            })?;
        if !std::mem::replace(&mut family_present[index], false) {
            return Err(format!(
                "or_deletion_state expects duplicate-free deletions; mask {value} repeats"
            ));
        }
        for (bit, frequency) in deleted_frequencies.iter_mut().enumerate() {
            *frequency += ((value >> bit) & 1) as i64;
        }
    }

    let mut subset_counts = family_present
        .iter()
        .map(|present| i64::from(*present))
        .collect::<Vec<_>>();
    for bit in 0..width {
        for mask in 0..cube_size {
            if mask & (1usize << bit) != 0 {
                subset_counts[mask] += subset_counts[mask ^ (1usize << bit)];
            }
        }
    }
    let mut union_counts = subset_counts
        .iter()
        .map(|count| {
            count
                .checked_mul(*count)
                .ok_or_else(|| "or_deletion_state pair count overflow".to_string())
        })
        .collect::<Result<Vec<_>, _>>()?;
    for bit in 0..width {
        for mask in 0..cube_size {
            if mask & (1usize << bit) != 0 {
                union_counts[mask] -= union_counts[mask ^ (1usize << bit)];
            }
        }
    }
    if union_counts
        .iter()
        .enumerate()
        .any(|(mask, count)| !family_present[mask] && *count != 0)
    {
        return Err("or_deletion_state deletions do not leave an OR-closed complement".to_string());
    }

    let deletable_members: Vec<i64> = family_present
        .iter()
        .enumerate()
        .filter_map(|(mask, present)| {
            if !present {
                return None;
            }
            (union_counts[mask] == 2 * subset_counts[mask] - 1).then_some(mask as i64)
        })
        .collect();
    let deleted_size = i64::try_from(family_present.iter().filter(|present| !**present).count())
        .map_err(|_| "or_deletion_state deletion count exceeds RAD integer range".to_string())?;
    let family_size = i64::try_from(cube_size)
        .map_err(|_| "or_deletion_state cube size exceeds RAD integer range".to_string())?
        - deleted_size;
    let half_cube = if width == 0 {
        0
    } else {
        (cube_size / 2) as i64
    };
    let family_frequencies: Vec<i64> = deleted_frequencies
        .iter()
        .map(|frequency| half_cube - frequency)
        .collect();
    let mut separation_witnesses = vec![0i64; width * width];
    for (member, present) in family_present.iter().enumerate() {
        if !present {
            continue;
        }
        for left in 0..width {
            for right in (left + 1)..width {
                if ((member >> left) & 1) != ((member >> right) & 1) {
                    separation_witnesses[left * width + right] += 1;
                }
            }
        }
    }
    let deletion_surpluses = deleted_frequencies
        .into_iter()
        .map(|frequency| 2 * frequency - deleted_size)
        .collect();
    let separating = (0..width).all(|left| {
        ((left + 1)..width).all(|right| {
            family_present.iter().enumerate().any(|(member, present)| {
                *present && ((member >> left) & 1) != ((member >> right) & 1)
            })
        })
    });
    // A removal preserves the effective labelled universe exactly when it
    // removes neither the last carrier of a coordinate nor the unique member
    // distinguishing a pair of coordinates.  This filters a closure-legal
    // frontier without rerunning the lattice transform per candidate.
    let effective_deletable_members = deletable_members
        .iter()
        .copied()
        .filter(|member| {
            let preserves_coverage = (0..width)
                .all(|bit| member & (1i64 << bit) == 0 || family_frequencies[bit] > 1);
            let preserves_separation = (0..width).all(|left| {
                ((left + 1)..width).all(|right| {
                    ((member >> left) & 1) == ((member >> right) & 1)
                        || separation_witnesses[left * width + right] > 1
                })
            });
            preserves_coverage && preserves_separation
        })
        .collect();

    Ok(OrDeletionState {
        family_size,
        family_frequencies,
        deletion_surpluses,
        deletable_members,
        effective_deletable_members,
        separating,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn closure_of_singletons_is_the_power_set() {
        let family = or_closure(&[1, 2, 4, 8]).unwrap();
        assert_eq!(family, (0..16).collect::<Vec<_>>());
        assert!(is_or_closed(&family).unwrap());
        assert_eq!(bit_frequencies(&family, 4).unwrap(), vec![8, 8, 8, 8]);
        let stats = or_closure_stats(&[1, 2, 4, 8], 4).unwrap();
        assert_eq!((stats.0, stats.1, stats.2), (16, vec![8; 4], true));
        assert_eq!(stats.3, or_closure_stats(&[8, 4, 2, 1], 4).unwrap().3);
    }

    #[test]
    fn closure_deduplicates_generators_and_uses_sparse_masks() {
        let family = or_closure(&[1 << 40, 3, 3]).unwrap();
        assert_eq!(family, vec![0, 3, 1 << 40, (1 << 40) | 3]);
        assert!(is_or_closed(&family).unwrap());
    }

    #[test]
    fn audit_rejects_duplicates_and_missing_joins() {
        assert!(!is_or_closed(&[0, 1, 1]).unwrap());
        assert!(!is_or_closed(&[0, 1, 2]).unwrap());
        assert_eq!(or_violation_count(&[0, 1, 2], 2).unwrap(), 2);
        assert_eq!(or_violation_count(&[0, 1, 2, 3], 2).unwrap(), 0);
        assert!(or_violation_count(&[0, 1, 1], 2).is_err());
        assert_eq!(
            or_deletable_members(&[0, 1, 2, 3], 2).unwrap(),
            vec![0, 1, 2]
        );
        assert_eq!(or_deletable_members(&[0, 2, 3], 2).unwrap(), vec![0, 2, 3]);
        assert!(or_deletable_members(&[0, 1, 2], 2).is_err());
        let initial = or_deletion_state(&[], 2).unwrap();
        assert_eq!(initial.family_size, 4);
        assert_eq!(initial.family_frequencies, vec![2, 2]);
        assert_eq!(initial.deletable_members, vec![0, 1, 2]);
        assert_eq!(initial.effective_deletable_members, vec![0, 1, 2]);
        assert!(initial.separating);
        let after_one = or_deletion_state(&[1], 2).unwrap();
        assert_eq!(after_one.family_size, 3);
        assert_eq!(after_one.family_frequencies, vec![1, 2]);
        assert_eq!(after_one.deletion_surpluses, vec![1, -1]);
        assert_eq!(after_one.effective_deletable_members, vec![0]);
        assert!(after_one.separating);
        assert!(or_deletion_state(&[3], 2).is_err());
    }

    #[test]
    fn masks_and_widths_are_checked() {
        assert!(or_closure(&[-1]).is_err());
        assert!(bit_frequencies(&[8], 3).is_err());
        assert!(bit_frequencies(&[0], 64).is_err());
        assert!(or_violation_count(&[8], 3).is_err());
        assert!(or_violation_count(&[0], 21).is_err());
        assert!(or_deletable_members(&[0], 21).is_err());
        assert!(or_deletion_state(&[], 21).is_err());
    }
}
