# gen_legion.py — content-volume extractor (fake-port round 20).
# Reads every champion's stats.ts (machine-generated from the era .ini,
# perfectly regular) and emits one rad content module per champion plus
# an index that imports them all. The point is VOLUME: 84 modules over
# one shared core, the layout a real port would use.
#
# Usage: py projects/dogfood/moba/tools/gen_legion.py

import re
from pathlib import Path

SRC = Path(r"H:\browser-moba\src\content\champions")
OUT = Path(__file__).resolve().parents[1] / "gen"

STAT_KEYS = [
    "hp", "hpPerLevel", "ad", "adPerLevel",
    "armor", "mr", "attackRange", "moveSpeed",
]


def parse_stats(text: str) -> dict:
    stats = {}
    for key in STAT_KEYS:
        m = re.search(rf"\b{key}:\s*(-?[0-9.]+)", text)
        if not m:
            raise ValueError(f"missing {key}")
        stats[key] = float(m.group(1))
    name = re.search(r"name:\s*'([^']+)'", text)
    stats["display"] = name.group(1) if name else "?"
    return stats


def fnum(v: float) -> str:
    s = f"{v:.6f}".rstrip("0").rstrip(".")
    return s if "." in s else s + ".0"


def main() -> None:
    champs = sorted(d.name for d in SRC.iterdir() if (d / "stats.ts").is_file())
    OUT.mkdir(parents=True, exist_ok=True)

    for champ in champs:
        stats = parse_stats((SRC / champ / "stats.ts").read_text(encoding="utf-8"))
        const = champ.upper()
        # ranged champions (era units: range >= 9 m) fight as casters,
        # melee as bruisers — the two brawl shapes legion_core provides
        shape = "ranged" if stats["attackRange"] >= 9.0 else "melee"
        body = f'''// GENERATED by tools/gen_legion.py from content/champions/{champ}/stats.ts
// ({stats["display"]} — era base stats; do not hand-edit)

use "legion_core.rad"

pub let {const} = ("{champ}", {fnum(stats["hp"])}, {fnum(stats["hpPerLevel"])}, {fnum(stats["ad"])}, {fnum(stats["adPerLevel"])}, {fnum(stats["armor"])}, {fnum(stats["mr"])}, {fnum(stats["attackRange"])}, {fnum(stats["moveSpeed"])}, "{shape}")

pub fn spawn_{champ}(team: int, at: (float, float)) -> entity {{
    return spawn_champ({const}, team, at)
}}
'''
        (OUT / f"c_{champ}.rad").write_text(body, encoding="utf-8", newline="\n")

    # the same 84 rows for the compiled backend: one source of truth,
    # two implementations, line-for-line trace parity
    rust_rows = "\n".join(
        '    ("{}", {}, {}, {}, {}, {}, {}, {}, {}),'.format(
            c,
            *(fnum(parse_stats((SRC / c / "stats.ts").read_text(encoding="utf-8"))[k]) for k in STAT_KEYS),
        )
        for c in champs
    )
    rust = f'''//! GENERATED by projects/dogfood/moba/tools/gen_legion.py — do not hand-edit.
//! The same 84 era stat rows the rad modules carry, for the compiled
//! backend: (name, hp, hp/lvl, ad, ad/lvl, armor, mr, range, ms).

pub const CHAMPS: [(&str, f64, f64, f64, f64, f64, f64, f64, f64); {len(champs)}] = [
{rust_rows}
];
'''
    rust_out = Path(__file__).resolve().parents[3] / "arena" / "src" / "gen_legion.rs"
    rust_out.write_text(rust, encoding="utf-8", newline="\n")

    uses = "\n".join(f'use "c_{c}.rad"' for c in champs)
    spawns = "\n".join(
        f"    roster << spawn_{c}(({i} % 2), (float({i} / 2) * 4.0, float({i} % 2) * 10.0))"
        for i, c in enumerate(champs)
    )
    index = f'''// GENERATED by tools/gen_legion.py — the full roster, one import each.

use "legion_core.rad"
{uses}

// every champion on the field: even index west, odd east
pub fn muster() -> list {{
    let mut roster = []
{spawns}
    return roster
}}
'''
    (OUT / "legion_index.rad").write_text(index, encoding="utf-8", newline="\n")
    print(f"generated {len(champs)} champion modules + legion_index.rad -> {OUT}")


if __name__ == "__main__":
    main()
