#!/usr/bin/env python3
"""Generate the CLI and browser-host API denominator from production owners."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CLI = ROOT / "adapters/cli/src/cli/arguments.rs"
WASM_RUNTIME = ROOT / "core/vm/src/wasm/runtime_api.rs"
WASM_CHUNK = ROOT / "core/vm/src/wasm/rendering_and_tests.rs"
OUTPUT = ROOT / "docs/host-api-surface.json"
MARKDOWN = ROOT / "docs/src/reference/generated/host-api-surface.md"


def text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def command_usages(source: str) -> list[str]:
    usages = re.findall(r"(?:Usage: )?\{program\} ([^\r\n\"]+)", source)
    result: list[str] = []
    for usage in usages:
        normalized = usage.replace("\\", "").strip()
        if normalized not in result:
            result.append(normalized)
    if not result:
        raise RuntimeError("no CLI command usages found")
    return result


def cli_options(source: str) -> list[str]:
    options = sorted(set(re.findall(r'"(--[a-z][a-z0-9-]*)', source)))
    if not options:
        raise RuntimeError("no CLI options found")
    return options


def public_functions(source: str) -> list[str]:
    names = re.findall(r"^\s*pub fn ([a-z][a-z0-9_]*)\s*\(", source, re.MULTILINE)
    result: list[str] = []
    for name in names:
        if name not in result:
            result.append(name)
    return result


def build() -> dict[str, object]:
    owners = [CLI, WASM_RUNTIME, WASM_CHUNK]
    digest = hashlib.sha256()
    owner_rows = []
    for path in owners:
        relative = path.relative_to(ROOT).as_posix()
        sha = hashlib.sha256(path.read_bytes()).hexdigest()
        digest.update(relative.encode())
        digest.update(b"\0")
        digest.update(bytes.fromhex(sha))
        owner_rows.append({"path": relative, "sha256": sha})
    cli_source = text(CLI)
    return {
        "formatVersion": 1,
        "ownerDigest": digest.hexdigest(),
        "owners": owner_rows,
        "cli": {
            "usages": command_usages(cli_source),
            "options": cli_options(cli_source),
        },
        "wasm": {
            "runtimeMethods": public_functions(text(WASM_RUNTIME)),
            "chunkMethods": public_functions(text(WASM_CHUNK)),
        },
    }


def render(surface: dict[str, object]) -> str:
    cli = surface["cli"]
    wasm = surface["wasm"]
    out = [
        "<!-- Generated by tooling/host_api_surface.py. Do not edit. -->\n",
        "# Compiler-owned host API surface\n\n",
        f"Owner digest: `{surface['ownerDigest']}`.\n\n",
        "This is the completeness denominator for the handwritten CLI, embedding, and WASM contracts.\n\n",
        "## CLI command forms\n\n| Usage after `rad` |\n|---|\n",
    ]
    out.extend(f"| `{usage.replace('|', '&#124;')}` |\n" for usage in cli["usages"])
    out.append("\n## CLI options\n\n| Option |\n|---|\n")
    out.extend(f"| `{option}` |\n" for option in cli["options"])
    out.append("\n## `RadRuntime` browser methods\n\n| Method | Source |\n|---|---|\n")
    out.extend(
        f"| `{name}` | `core/vm/src/wasm/runtime_api.rs` |\n"
        for name in wasm["runtimeMethods"]
    )
    out.append("\n## `WasmChunk` browser methods\n\n| Method | Source |\n|---|---|\n")
    out.extend(
        f"| `{name}` | `core/vm/src/wasm/rendering_and_tests.rs` |\n"
        for name in wasm["chunkMethods"]
    )
    return "".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    surface = build()
    encoded = json.dumps(surface, indent=2, ensure_ascii=False) + "\n"
    markdown = render(surface)
    if args.check:
        if (
            not OUTPUT.is_file()
            or OUTPUT.read_text(encoding="utf-8") != encoded
            or not MARKDOWN.is_file()
            or MARKDOWN.read_text(encoding="utf-8") != markdown
        ):
            print("stale host API surface: run tooling/host_api_surface.py")
            return 1
        print(
            "host API surface current: "
            f"{len(surface['cli']['usages'])} command forms, "
            f"{len(surface['cli']['options'])} options, "
            f"{len(surface['wasm']['runtimeMethods'])} runtime methods"
        )
        return 0
    OUTPUT.write_text(encoded, encoding="utf-8", newline="\n")
    MARKDOWN.write_text(markdown, encoding="utf-8", newline="\n")
    print(f"{OUTPUT.relative_to(ROOT)} + {MARKDOWN.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
